#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x022166C0FF3C84E3 (csmall@debian.org)
#
Name     : procps-ng
Version  : 3.3.15
Release  : 44
URL      : https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-3.3.15.tar.xz
Source0  : https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-3.3.15.tar.xz
Source1 : https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-3.3.15.tar.xz.asc
Summary  : Library to control and query process state
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ GPL-3.0+ LGPL-2.0 LGPL-2.0+
Requires: procps-ng-bin = %{version}-%{release}
Requires: procps-ng-lib = %{version}-%{release}
Requires: procps-ng-license = %{version}-%{release}
Requires: procps-ng-locales = %{version}-%{release}
Requires: procps-ng-man = %{version}-%{release}
BuildRequires : dejagnu
BuildRequires : expect
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)
BuildRequires : systemd-dev
BuildRequires : tcl
Patch1: break.patch

%description
No detailed description available

%package bin
Summary: bin components for the procps-ng package.
Group: Binaries
Requires: procps-ng-license = %{version}-%{release}

%description bin
bin components for the procps-ng package.


%package dev
Summary: dev components for the procps-ng package.
Group: Development
Requires: procps-ng-lib = %{version}-%{release}
Requires: procps-ng-bin = %{version}-%{release}
Provides: procps-ng-devel = %{version}-%{release}
Requires: procps-ng = %{version}-%{release}

%description dev
dev components for the procps-ng package.


%package doc
Summary: doc components for the procps-ng package.
Group: Documentation
Requires: procps-ng-man = %{version}-%{release}

%description doc
doc components for the procps-ng package.


%package extras
Summary: extras components for the procps-ng package.
Group: Default

%description extras
extras components for the procps-ng package.


%package lib
Summary: lib components for the procps-ng package.
Group: Libraries
Requires: procps-ng-license = %{version}-%{release}

%description lib
lib components for the procps-ng package.


%package license
Summary: license components for the procps-ng package.
Group: Default

%description license
license components for the procps-ng package.


%package locales
Summary: locales components for the procps-ng package.
Group: Default

%description locales
locales components for the procps-ng package.


%package man
Summary: man components for the procps-ng package.
Group: Default

%description man
man components for the procps-ng package.


%prep
%setup -q -n procps-ng-3.3.15
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1564460324
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-lto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-lto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-lto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-lto -fno-semantic-interposition "
%configure --disable-static --exec-prefix=/ --enable-watch8bit --with-systemd
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check ||:

%install
export SOURCE_DATE_EPOCH=1564460324
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/procps-ng
cp COPYING %{buildroot}/usr/share/package-licenses/procps-ng/COPYING
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/procps-ng/COPYING.LIB
%make_install
%find_lang procps-ng
## Remove excluded files
rm -f %{buildroot}/usr/bin/uptime
rm -f %{buildroot}/usr/share/man/man1/uptime.1
## install_append content
mv %{buildroot}/usr/bin/top %{buildroot}/usr/bin/top2
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/free
/usr/bin/kill
/usr/bin/pgrep
/usr/bin/pidof
/usr/bin/pkill
/usr/bin/pmap
/usr/bin/ps
/usr/bin/pwdx
/usr/bin/sysctl
/usr/bin/tload
/usr/bin/top2
/usr/bin/vmstat
/usr/bin/w
/usr/bin/watch

%files dev
%defattr(-,root,root,-)
/usr/include/proc/alloc.h
/usr/include/proc/devname.h
/usr/include/proc/escape.h
/usr/include/proc/numa.h
/usr/include/proc/procps.h
/usr/include/proc/pwcache.h
/usr/include/proc/readproc.h
/usr/include/proc/sig.h
/usr/include/proc/slab.h
/usr/include/proc/sysinfo.h
/usr/include/proc/version.h
/usr/include/proc/wchan.h
/usr/include/proc/whattime.h
/usr/lib64/libprocps.so
/usr/lib64/pkgconfig/libprocps.pc
/usr/share/man/man3/openproc.3
/usr/share/man/man3/readproc.3
/usr/share/man/man3/readproctab.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/procps\-ng/*

%files extras
%defattr(-,root,root,-)
/usr/bin/slabtop

%files lib
%defattr(-,root,root,-)
/usr/lib64/libprocps.so.7
/usr/lib64/libprocps.so.7.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/procps-ng/COPYING
/usr/share/package-licenses/procps-ng/COPYING.LIB

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/free.1
/usr/share/man/man1/kill.1
/usr/share/man/man1/pgrep.1
/usr/share/man/man1/pidof.1
/usr/share/man/man1/pkill.1
/usr/share/man/man1/pmap.1
/usr/share/man/man1/procps.1
/usr/share/man/man1/ps.1
/usr/share/man/man1/pwdx.1
/usr/share/man/man1/slabtop.1
/usr/share/man/man1/tload.1
/usr/share/man/man1/top.1
/usr/share/man/man1/w.1
/usr/share/man/man1/watch.1
/usr/share/man/man5/sysctl.conf.5
/usr/share/man/man8/sysctl.8
/usr/share/man/man8/vmstat.8

%files locales -f procps-ng.lang
%defattr(-,root,root,-)

